/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/tree3-transformed.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, 0, 0]}
        position={[3, 0, 1]}
        scale={[0.15, 0.15, 0.15]}
      >
        <mesh geometry={nodes.SpookyTree_01001_1.geometry} />
        <mesh geometry={nodes.SpookyTree_01001_2.geometry} />
        <mesh geometry={nodes.SpookyTree_01001_3.geometry} />
      </group>
    </group>
  );
}

useGLTF.preload("/tree3-transformed.glb");
